name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install app dependencies
        run: npm ci

      - name: Install functions dependencies
        run: npm ci
        working-directory: functions

      - name: Build app
        run: npm run build

      - name: Test functions
        run: npm run test:functions

      - name: Test Firestore rules
        run: npm run test:rules
